# Generated by Django 2.2.2 on 2019-06-16 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True, verbose_name='Время создания')),
                ('name', models.CharField(max_length=128, verbose_name='Название события')),
                ('description', models.TextField(verbose_name='Описание')),
                ('end_date', models.DateTimeField(verbose_name='Дата окончания события')),
            ],
            options={
                'verbose_name': 'Покупка',
                'verbose_name_plural': 'Покупки',
                'ordering': ['end_date'],
            },
        ),
    ]
